Post.destroy_all

Post.create(title: "Post #1", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consequatur enim vero magni dolor fuga sed aliquid praesentium. Praesentium libero ipsa reiciendis error veritatis maiores quibusdam possimus debitis minus voluptatum.
Repellendus, veniam tempore corrupti accusamus distinctio cupiditate quisquam debitis, qui quo temporibus aliquam impedit nihil. In quaerat, ab, animi, nam iure debitis nostrum sunt recusandae saepe dolorum eius accusamus molestiae!
Deleniti reiciendis at ut eaque ea nostrum! Doloribus reprehenderit sed aut atque placeat deserunt adipisci, commodi minima temporibus accusantium possimus nulla unde incidunt quia praesentium vitae, nisi accusamus nam mollitia.
Nulla impedit repudiandae exercitationem deserunt laborum est facilis nostrum. Corporis voluptatibus cumque numquam dolore voluptate quaerat quo praesentium placeat maiores provident rem suscipit hic dicta aliquid eveniet eos, qui commodi.
In praesentium debitis pariatur aut, consectetur perferendis quia dolorem magnam culpa quos a eligendi numquam ipsa alias accusamus possimus qui vitae natus aliquam tenetur amet quo commodi. Saepe, placeat eum!")
Post.create(title: "Post #2", content: "Quasi molestiae maiores cupiditate maxime quod odio animi aperiam, repudiandae optio quia iste unde rem sint magni labore velit! Necessitatibus neque fugit fuga inventore non atque illo reprehenderit officiis aliquid!
Minus similique perferendis rerum dolores nihil facere, sequi earum laudantium qui tenetur odio? Velit iure, repellat totam eius ex libero culpa exercitationem similique, necessitatibus fugit distinctio ea voluptatem placeat porro.
Incidunt iusto dolore tenetur sit consequatur, corrupti excepturi dolores illo eius expedita sequi voluptas perferendis eaque! Corporis, eum! Consequatur iusto fugiat consequuntur quae non quaerat, aliquid delectus accusantium magnam numquam?
Quam earum quos ducimus ab culpa animi rerum cupiditate libero. Possimus quisquam facilis ea numquam dignissimos error est fuga eveniet? Aut magni, hic rerum iste in esse amet cupiditate eligendi.
Hic aperiam fugiat incidunt, aspernatur, accusantium architecto illo reprehenderit nulla quis delectus numquam unde nam maiores nihil. Ex obcaecati ad omnis. Voluptatibus, debitis itaque. Quam iusto quasi mollitia placeat illo.")
Post.create(title: "Post #3", content: "Officia suscipit veniam atque deserunt, quo iure? Laborum totam ut, quis sint quaerat nulla facere. Eaque laboriosam, illum id quia tenetur ipsam, voluptatibus temporibus veritatis asperiores alias ullam optio. A.
Ut sunt eius qui nam debitis reiciendis molestias exercitationem officia minus assumenda, consequatur harum vero voluptatibus fugiat accusantium nemo quidem mollitia sapiente dolores quia asperiores iure at voluptatum corporis. Iusto?
Ullam, voluptatem ab blanditiis est aspernatur ea cum laboriosam nisi sunt officiis voluptatibus, sapiente labore voluptate numquam ex minus, earum iusto accusantium assumenda voluptates sed nihil! Distinctio laborum corrupti vel!
Vitae dolorem magni ad voluptate delectus ex, laudantium eaque tempore velit blanditiis doloremque in tempora quos commodi, sunt minima consequuntur distinctio, est fuga. Laudantium voluptates aut a animi, blanditiis earum.
Voluptates ratione aperiam nesciunt accusantium ea, suscipit atque minima illo aut quae saepe id aliquam? Ad delectus minima enim repellendus distinctio, deserunt, hic ipsa temporibus cupiditate magnam voluptatem dolorum sapiente?")
Post.create(title: "Post #4", content: "Distinctio necessitatibus eligendi fugiat, id eius corporis eos voluptate quas facere ullam doloribus quidem reprehenderit voluptatem ipsum, unde accusamus temporibus quos voluptates cupiditate. Animi corporis veritatis consectetur error. Expedita, corporis.
Exercitationem, vel. Nam aliquid iure distinctio quod. Quam aliquid atque fugiat distinctio iure deserunt error amet, sed quod quasi tempore, iusto quis quas quidem adipisci repudiandae placeat temporibus ea. Harum!
Officia nihil deserunt consequatur voluptatem praesentium saepe distinctio? Dolorum accusantium aut, quos odit ab culpa dolor blanditiis nisi, aperiam repellendus sunt laborum, veritatis ratione illum quae exercitationem quaerat asperiores iusto!
Quas eligendi asperiores, placeat omnis eius repudiandae deleniti illum architecto. Harum esse distinctio adipisci inventore tempora ut, incidunt necessitatibus, quidem, neque magni dolorem. Unde corrupti nostrum officia dolore inventore aliquam?
Blanditiis alias animi rerum, adipisci voluptates nemo nihil delectus ipsa velit vel temporibus modi laudantium corporis enim dignissimos pariatur fugiat eveniet veniam voluptatem eaque accusantium. Perspiciatis mollitia necessitatibus dicta doloribus.
Quidem esse atque ducimus saepe. Odio a necessitatibus repellendus pariatur perferendis reprehenderit mollitia fuga praesentium nisi accusantium nobis consequatur corporis asperiores sapiente cumque odit iste inventore, in est rerum. Incidunt?")
Post.create(title: "Post #5", content: "Quia rerum quae tempore nihil ut aut. Obcaecati laborum doloribus accusamus harum tempora praesentium soluta magni sunt sint libero explicabo tempore excepturi, ducimus ea vitae? Officiis accusantium veritatis voluptates ipsam?
Dignissimos, unde et sequi perspiciatis odit totam ab sunt nihil aspernatur reprehenderit facere quibusdam nulla, tempora tempore, deserunt expedita veritatis optio harum dolore eligendi eius delectus quaerat officia neque. Dicta!
Repudiandae nihil doloribus quis fugiat maiores? Minus nam quos autem ipsam deleniti, accusantium maxime temporibus architecto animi id explicabo repellat qui dolorum, esse libero ipsa ipsum! Veniam hic illo corrupti!
Praesentium ea veniam rem recusandae modi optio odio reiciendis earum dolor fugiat, ex atque eligendi at ad laudantium accusantium beatae vero similique itaque dicta sit qui libero, veritatis suscipit. Alias.")
